import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import authRouter from "./auth";
import usersRouter from "./users";
import schoolsRouter from "./schools";
import medicalRouter from "./medical";
import shopsRouter from "./shops";
import listingsRouter from "./listings";
import busesRouter from "./buses";
import jobsRouter from "./jobs";
import eventsRouter from "./events";
import noticesRouter from "./notices";
import emergencyRouter from "./emergency";
import statsRouter from "./stats";
import reelsRouter from "./reels";
import socialRouter from "./social";
import notificationsRouter from "./notifications";
import messagesRouter from "./messages";
import cartRouter from "./cart";
import userShopsRouter from "./user-shops";
import jobApplicationsRouter from "./job-applications";
import postsRouter from "./posts";
import snapsRouter from "./snaps";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/schools", schoolsRouter);
router.use("/medical", medicalRouter);
router.use("/shops", shopsRouter);
router.use("/listings", listingsRouter);
router.use("/buses", busesRouter);
router.use("/jobs", jobsRouter);
router.use("/events", eventsRouter);
router.use("/notices", noticesRouter);
router.use("/emergency", emergencyRouter);
router.use("/stats", statsRouter);
router.use("/reels", reelsRouter);
router.use(socialRouter);
router.use(jobApplicationsRouter);
router.use(postsRouter);
router.use(snapsRouter);
router.use("/notifications", notificationsRouter);
router.use("/messages", messagesRouter);
router.use("/cart", cartRouter);
router.use("/user-shops", userShopsRouter);

export default router;
